#!/usr/bin/env bash

sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts

grep -q "^8\.8\.8\.8[[:space:]]\+facebook\.com$" /etc/hosts || \
echo "8.8.8.8 facebook.com" >> /etc/hosts
